CREATE OR REPLACE PACKAGE BODY PKG_TEST_ME IS

  --
  -- This 
  --
  FUNCTION FC_TEST_ME(PPARAM1 IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    IF PPARAM1 IS NULL THEN
      RETURN NULL;
    ELSIF PPARAM1 = '1' THEN
      RETURN 1;
    ELSE
      RETURN 0;
    END IF;
  END FC_TEST_ME;

  PROCEDURE PR_TEST_ME(PSNAME IN VARCHAR2) IS
  BEGIN
    IF PSNAME IS NULL THEN
      NULL;
    ELSE
      INSERT INTO TO_TEST_ME (SNAME) VALUES (PSNAME);
      COMMIT;
    END IF;
  END PR_TEST_ME;

END PKG_TEST_ME;
/