ALTER SESSION SET CURRENT_SCHEMA = CODE_OWNER;

--
-- This is a table used to demonstrate the UNIT test framework.
--
CREATE TABLE TO_TEST_ME
(
  SNAME VARCHAR2(10)
);
/

--
-- This package is used TO demonstrate the utPL/SQL possibilities 
--
CREATE OR REPLACE PACKAGE CODE_OWNER.PKG_TEST_ME AS
  FUNCTION FC_TEST_ME(PPARAM1 IN VARCHAR2) RETURN NUMBER;
  PROCEDURE PR_TEST_ME(PSNAME IN VARCHAR2);
END PKG_TEST_ME;
/

CREATE OR REPLACE PACKAGE BODY PKG_TEST_ME IS
  --
  -- This 
  --
  FUNCTION FC_TEST_ME(PPARAM1 IN VARCHAR2) RETURN NUMBER IS
  BEGIN
    IF PPARAM1 IS NULL THEN
      RETURN NULL;
    ELSIF PPARAM1 = '1' THEN
      RETURN 1;
    ELSE
      RETURN 0;
    END IF;
  END FC_TEST_ME;

  PROCEDURE PR_TEST_ME(PSNAME IN VARCHAR2) IS
  BEGIN
    IF PSNAME IS NULL THEN
      NULL;
    ELSE
      INSERT INTO TO_TEST_ME (SNAME) VALUES (PSNAME);
      COMMIT;
    END IF;
  END PR_TEST_ME;

END PKG_TEST_ME;
/
